name: ETL Workflow for Group 20

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ggplot2", "dplyr", "readr", "tidyr", "RSQLite", "generator","DBI","lubridate"))'
      - name: Execute R script to update the database with new entry (second data phase), before appending, it compares new data with the existing database to prevent duplicate entries in database
        run: |
          Rscript R/Load_data.R
      - name: Execute R script to validate the new entries, their formats and referential integrity for each table
        run: |
          Rscript R/Table_Creation.R    
      - name: Execute R script to validate the data
        run: |
          Rscript R/Validation.R    
      - name: Execute R script to update the analysis 
        run: |
          Rscript Data_Analysis/DataAnalysis.R 
      - name: Add collaborator 1
        run: |
          git config --global user.email "marwahapulkit22@gmail.com"
          git config --global user.name "Pulkit2206"
      - name: Add collaborator 2
        run: | 
          git config --global user.email "twaseenshazaib@hotmail.co.uk"
          git config --global user.name "shazaibt"
      - name: Add collaborator 3
        run: | 
          git config --global user.email "Jiayue.liu.3@warwick.ac.uk"
          git config --global user.name "Leaaaaaaausername"
      - name: Add collaborator 4
        run: | 
          git config --global user.email "amaliasharfina@gmail.com"
          git config --global user.name "amaliasharfina"
      - name: Add collaborator 5
        run: | 
          git config --global user.email "namit2000.singh@gmail.com"
          git config --global user.name "Namitt"
      - name: Add collaborator 6
        run: | 
          git config --global user.email "chananya.yodkaew@warwick.ac.uk"
          git config --global user.name "Chananya2027735" 
      - name: Commit files
        run: |
          git add database/database.db
          git add Rplots.pdf
          git commit -m "Add plot figure"
     
